# Setup
title:               IFT3700 - NHL Data Deep Dive
tagline:             'Exploring the dynamics of the NHL through data.'
description:         >
  A collaborative blog documenting the IFT3700 project on NHL statistics and performance analytics.
  This site details our methods, models, visualizations, and findings throughout the data analysis process.
  Built with <a href="https://jekyllrb.com" target="_blank">Jekyll</a> using the Lanyon theme.

baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
authors:
 xavier_drolet:
    name:            "Xavier Drolet"
    email:           "xavier.drolet.2@umontreal.ca"
    url:             "https://www.linkedin.com/in/xavier-drolet"
 alexis_archambault:
    name:            "Alexis Archambault"
    email:           "" # TODO
    url:             ""
 fauverick:
    name:            "Cao Hung Nguyen"
    email:           "" # TODO
    url:             ""

# Default author info
author:
  name:              "IFT3700 NHL Project Team"
  url:               ""
  email:             ""

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
